### ISSUE TITLE
Text to clip still results in an error message (ASSFoundation v0.3.2 alpha)

### ISSUE THREAD

**Issue by SchRita** [TypesettingTools/ASSFoundation#3]
As requested, here's the ass file:
http://pastebin.com/9ShVadN5
and here:
http://www.filedropper.com/texttocliptestschrita

The Nudge settings should be the same. ASSFoundation is v0.3.2 alpha.
If you need more information, I can send you any data you want. ^^
Thank you for your help.

**Comment by line0** [comment]
Thanks, it didn't occur to me to test this one without any tag block present. See commit for details
